[versions]
autoService = "1.0"

[libraries.checkerframework-qual]
module = "org.checkerframework:checker-qual"
version = "3.13.0"

[libraries.log4j-bom]
module = "org.apache.logging.log4j:log4j-bom"
version = "2.14.1"

[libraries.log4j-api]
module = "org.apache.logging.log4j:log4j-api"

[libraries.junit-bom]
module = "org.junit:junit-bom"
version = "5.7.1"

[libraries.junit-jupiter-api]
module = "org.junit.jupiter:junit-jupiter-api"

[libraries.junit-jupiter-engine]
module = "org.junit.jupiter:junit-jupiter-engine"

[libraries.truth]
module = "com.google.truth:truth"
version = "1.1.2"
